### ISSUE TITLE
getaddrinfo 返回 11001 但是 gai_strerror 返回了空字符串

### ISSUE THREAD

**Issue by ylme** [cloudwu/lsocket#6]
系统：Windows 10
平台：msys2

执行 `lsocket.connect(ip, port)` 传入的 ip 的地址格式正确，但指向一个不存在的主机。就想测试下这种情况，发现 `lsocket.connect` 返回的第二个参数是空串，定位是下面这行代码返回的：

https://github.com/cloudwu/lsocket/blob/8e7752c5b06b889e2d7f91ebff769e0b2b70574d/lsocket.c#L419

Windows 系统真的神奇，就期望着如果传入了不存在的主机，`lsocket.connect` 的第二个参数能不能返回相应的字符串描述。不过目前倒也不影响使用。

**Comment by cloudwu** [comment]
这个库不是为 windows 开发的。所有 windows 支持只保证勉强可用。

**Comment by ylme** [comment]
那先不管这个了，反正也不影响使用。
