### ISSUE TITLE
windows下tcp模式send数据出错

### ISSUE THREAD

**Issue by nivrrex** [cloudwu/lsocket#7]
-------------------------------代码-------------------------------
local lsocket = require("lsocket")

function split(str,reps)
    if string.find(str,reps) ~= nil then
        local resultStrList = {}
        string.gsub(str,'[^'..reps..']+',function (w)
            table.insert(resultStrList,w)
        end)
        return resultStrList
    else return nil
    end
end

server ="8.8.8.8"
port = 53
host = "baidu"

local client, err = lsocket.connect("tcp",server,port)
if not client then
    print("error: "..err)
    return nil
end

math.randomseed(os.time())
local data = string.char(math.random(1,255),math.random(1,255))
data = data .. string.char(0x01,0x00,0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x00)
local temp = split(host,".")
for i,v in pairs(temp) do
    data = data .. string.char(string.len(v))
    for j=1,string.len(v) do
        data = data .. string.sub(v,j,j)
    end
end
data = data .. string.char(0x00,0x00,0x01,0x00,0x01)
data = string.char(0x00,string.len(data)) .. data

ok, err = client:send(data)
if not ok then print("error: "..err) end
-------------------------------代码-------------------------------

最近在学习写dns查询的测试代码，当在windows下执行时，tcp模式下send，会出现"error: Unknown error"错误，但是同样的代码在linux环境下执行时，会正常运行，不知道是我编译的问题，还是库的问题，希望能指导解决

**Comment by cloudwu** [comment]
https://github.com/cloudwu/lsocket/blob/master/win_compat.c#L242

把这里的 errcode 输出一下，看看是什么。

**Comment by nivrrex** [comment]
win_compat.c#L242下加了个printf，还是执行上边的lua代码，出现的错误代码如下：
10035
10035
10057
10057
10057
error: Unknown error

**Comment by nivrrex** [comment]
wsa_errno() {
	int errcode = WSAGetLastError();
	printf("%d\n",errcode);
	return wsa_error_to_errno(errcode);
}

**Comment by cloudwu** [comment]
https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2  WSAENOTCONN 10057  Socket is not connected.

而且我不认为你可以对 8.8.8.8:53 建立起 tcp 连接。

**Comment by nivrrex** [comment]
8.8.8.8:53 是可以建立起 tcp 连接的。在我的网络环境下也是可以正常连接的，同样类似的代码用luasocket可以实现。

我又逐步调试了下，发现在lsocket.connect("tcp",server,port)时产生了两个10035错误，Google结果是
**非阻塞模式时，connect不会马上返回，它需要时间来确定，可能会产生10035错误**
所以上边的代码中，我在connect后立即执行send，导致了后续的10057错误

然后按samples/httpclient.lua的例子中，在client:send前加上了
lsocket.select(nil, {client})
进行等待，然后就可以正常send了，不会出现10057错误
如果我把lsocket.select(nil, {client})替换成模拟的的sleep函数，也是可以正常执行的

我又在linux环境(mipsel openwrt)下做了实验，同样的代码
lsocket.connect("tcp",server,port)不会产生10035错误，只能判断是windows环境和linux环境对非阻塞环境下socket编程处理的不同了

**Comment by cloudwu** [comment]
你需要 select 判断端口是否可写来确定连接是否建立。这个在文档中有写。https://github.com/cloudwu/lsocket/blob/master/doc/README#L96-L101

**Comment by nivrrex** [comment]
嗯，之前没有注意，我再好好研究下
感谢指导
